### ISSUE TITLE
cannot access org.elasticsearch.action.admin.indices.mapping.put.PutMappingResponse

### ISSUE THREAD

**Issue by ganil89** [codelibs/elasticsearch-cluster-runner#27]
Hi,

I am using elastic search 6.5.4 and added below dependency in pom.xml
<dependency>
			<groupId>org.codelibs</groupId>
			<artifactId>elasticsearch-cluster-runner</artifactId>
			<version>5.5.2.0</version>
		</dependency>
As mentioned, I tried using the runner for my test cases. My Test case class has compile time error.
cannot access org.elasticsearch.action.admin.indices.mapping.put.PutMappingResponse.

Please let me know the solution.

**Comment by marevol** [comment]
Try version `6.5.4.0`.

**Comment by ganil89** [comment]
you mean elastic search or codelibs version

**Comment by marevol** [comment]
elasticsearch-cluster-runner 6.5.4.0 is for elasticsearch 6.5.4.

**Comment by ganil89** [comment]
Thank you,

I have an other issue with this

Caused by: java.lang.ClassCastException: org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:142)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:119)
	at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.buildNodeSettings(ElasticsearchClusterRunner.java:496)
	at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:384)
	... 15 more

**Comment by marevol** [comment]
You can check dependencies for this project in [pom.xml](https://github.com/codelibs/elasticsearch-cluster-runner/blob/master/pom.xml#L131-L264).
It's better to check your dependencies in your project.

**Comment by ganil89** [comment]
I have taken all the dependencies from this project pom.xml

**Comment by marevol** [comment]
I could not reproduce it. Could you provide steps or all code to reproduce it.

**Comment by wallner** [comment]
I had the same problem too. I am using Spring Data Elasticsearch. In a Spring Boot project. The problem is that `spring-boot-starter` pulls in `spring-boot-starter-logging`. If you exclude it, it works. This is the relevant part of my `pom.xml`:
``` 
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.codelibs</groupId>
      <artifactId>elasticsearch-cluster-runner</artifactId>
      <version>6.8.4.0</version>
      <scope>test</scope>
    </dependency>
```

An interesting observation: The `spring-data-elasticsearch` release train working with the current spring boot version (2.2) pulls in Elasticsearch 6.8.5 but there is no corresponding elasticsearch-cluster-runner version.

Thank You for your Work!

**Comment by foal** [comment]
@wallner - it is easy. Elasticsearch-cluster-runner works only with log4j. It depends on log4j-core and uses the log4j core classes in runtime. Spring boot starter logger add to the classpath SLF4j bridge that causes exception above

**Comment by jlfeld1** [comment]
We shouldn't have to change our applications logging implementation in order to use this library.

**Comment by foal** [comment]
It will be great if Elasticsearch-cluster-runner will not depend on log4j implementation. Only on log4j interfaces. It will allow to use it without patching sources each time than I need to run integration tests in spring boot application.

See https://stackoverflow.com/questions/54036773/unable-to-initialize-log4j-slf4jloggercontextfactory for example
