### ISSUE TITLE
latest version problem

### ISSUE THREAD

**Issue by sangkyunkim89** [codelibs/elasticsearch-cluster-runner#43]
I'm so glad I found this test tool that's really good for testing lucene! By the way
Runner version 8.10.2 doesn't seem to support Lucene 8.10.1!
It seems to be compatible with 8.7.0, can you please enable it?

**Comment by marevol** [comment]
It depends on elasticsearch. So, if elasticsearch uses the version of Lucene, this runner will provide it.

**Comment by sangkyunkim89** [comment]
@marevol 

Version must be upgraded to [8.10.1] is still set to [8.7.0]
java.lang.AssertionError: Version must be upgraded to [8.10.1] is still set to [8.7.0]

```
+--- org.elasticsearch:elasticsearch:7.10.2
|    +--- org.elasticsearch:elasticsearch-core:7.10.2
|    +--- org.elasticsearch:elasticsearch-secure-sm:7.10.2
|    +--- org.elasticsearch:elasticsearch-x-content:7.10.2
|    |    +--- org.elasticsearch:elasticsearch-core:7.10.2
|    |    +--- org.yaml:snakeyaml:1.26
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.10.4
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.10.4
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.4
|    |    \--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.10.4
|    +--- org.elasticsearch:elasticsearch-geo:7.10.2
|    +--- org.apache.lucene:lucene-core:8.7.0 -> 8.10.1
|    +--- org.apache.lucene:lucene-analyzers-common:8.7.0 -> 8.10.1
|    |    \--- org.apache.lucene:lucene-core:8.10.1
|    +--- org.apache.lucene:lucene-backward-codecs:8.7.0
|    +--- org.apache.lucene:lucene-grouping:8.7.0
|    +--- org.apache.lucene:lucene-highlighter:8.7.0
|    +--- org.apache.lucene:lucene-join:8.7.0
|    +--- org.apache.lucene:lucene-memory:8.7.0
|    +--- org.apache.lucene:lucene-misc:8.7.0
|    +--- org.apache.lucene:lucene-queries:8.7.0
|    +--- org.apache.lucene:lucene-queryparser:8.7.0
|    +--- org.apache.lucene:lucene-sandbox:8.7.0
|    +--- org.apache.lucene:lucene-spatial-extras:8.7.0
|    +--- org.apache.lucene:lucene-spatial3d:8.7.0
|    +--- org.apache.lucene:lucene-suggest:8.7.0
|    +--- org.elasticsearch:elasticsearch-cli:7.10.2
|    |    +--- net.sf.jopt-simple:jopt-simple:5.0.2
|    |    \--- org.elasticsearch:elasticsearch-core:7.10.2
|    +--- com.carrotsearch:hppc:0.8.1
|    +--- joda-time:joda-time:2.10.4
|    +--- com.tdunning:t-digest:3.2
|    +--- org.hdrhistogram:HdrHistogram:2.1.9
|    +--- org.apache.logging.log4j:log4j-api:2.11.1
|    \--- org.elasticsearch:jna:5.5.0
+--- org.apache.logging.log4j:log4j-core:2.9.1 -> 2.11.1
|    \--- org.apache.logging.log4j:log4j-api:2.11.1
+--- org.codelibs:analyzers:8.10.1.0
|    +--- org.apache.lucene:lucene-analyzers-common:8.10.1 (*)
|    \--- org.apache.lucene:lucene-analyzers-kuromoji:8.10.1
|         +--- org.apache.lucene:lucene-analyzers-common:8.10.1 (*)
|         \--- org.apache.lucene:lucene-core:8.10.1
+--- org.apache.lucene:lucene-core:8.10.1
+--- org.apache.lucene:lucene-analyzers-common:8.10.1 (*)
+--- org.apache.commons:commons-lang3:3.5
+--- commons-codec:commons-codec:1.13
+--- com.google.guava:guava:28.1-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:2.8.1
|    +--- com.google.errorprone:error_prone_annotations:2.3.2
|    +--- com.google.j2objc:j2objc-annotations:1.3
|    \--- org.codehaus.mojo:animal-sniffer-annotations:1.18
+--- org.apache.lucene:lucene-analyzers-nori:8.10.1
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
\--- org.codelibs:elasticsearch-cluster-runner:7.10.2.0
     +--- org.elasticsearch:elasticsearch:7.10.2 (*)
     +--- org.codelibs.elasticsearch.lib:plugin-classloader:7.10.2
     +--- org.codelibs.elasticsearch.module:aggs-matrix-stats:7.10.2
     +--- org.codelibs.elasticsearch.module:analysis-common:7.10.2
     +--- org.codelibs.elasticsearch.module:ingest-common:7.10.2
     |    +--- org.codelibs.elasticsearch.lib:dissect:7.10.2
     |    +--- org.codelibs.elasticsearch.lib:grok:7.10.2
     |    +--- org.jruby.jcodings:jcodings:1.0.44
     |    \--- org.jruby.joni:joni:2.1.29
     |         \--- org.jruby.jcodings:jcodings:1.0.44
     +--- org.codelibs.elasticsearch.module:ingest-user-agent:7.10.2
     +--- org.codelibs.elasticsearch.module:lang-expression:7.10.2
     |    +--- org.antlr:antlr4-runtime:4.5.1-1 -> 4.5.3
     |    \--- org.apache.lucene:lucene-expressions:8.7.0
     |         +--- org.apache.lucene:lucene-core:8.7.0 -> 8.10.1
     |         \--- org.antlr:antlr4-runtime:4.5.1-1 -> 4.5.3
     +--- org.codelibs.elasticsearch.module:lang-mustache:7.10.2
     |    \--- com.github.spullara.mustache.java:compiler:0.9.6
     +--- org.codelibs.elasticsearch.module:lang-painless:7.10.2
     |    +--- org.antlr:antlr4-runtime:4.5.3
     |    +--- org.ow2.asm:asm:7.2
     |    +--- org.ow2.asm:asm-analysis:7.2
     |    |    \--- org.ow2.asm:asm-tree:7.2
     |    |         \--- org.ow2.asm:asm:7.2
     |    +--- org.ow2.asm:asm-commons:7.2
     |    |    +--- org.ow2.asm:asm:7.2
     |    |    +--- org.ow2.asm:asm-tree:7.2 (*)
     |    |    \--- org.ow2.asm:asm-analysis:7.2 (*)
     |    +--- org.ow2.asm:asm-tree:7.2 (*)
     |    +--- org.ow2.asm:asm-util:7.2
     |    |    +--- org.ow2.asm:asm:7.2
     |    |    +--- org.ow2.asm:asm-tree:7.2 (*)
     |    |    \--- org.ow2.asm:asm-analysis:7.2 (*)
     |    \--- org.codelibs.elasticsearch.module:scripting-painless-spi:7.10.2
     |         \--- org.elasticsearch:elasticsearch:7.10.2 (*)
     +--- org.codelibs.elasticsearch.module:mapper-extras:7.10.2
     +--- org.codelibs.elasticsearch.module:parent-join:7.10.2
     +--- org.codelibs.elasticsearch.module:percolator:7.10.2
     +--- org.codelibs.elasticsearch.module:rank-eval:7.10.2
     +--- org.codelibs.elasticsearch.module:reindex:7.10.2
     |    +--- commons-codec:commons-codec:1.11 -> 1.13
     |    +--- commons-logging:commons-logging:1.1.3 -> 1.2
     |    +--- org.elasticsearch.client:elasticsearch-rest-client:7.10.2
     |    |    +--- org.apache.httpcomponents:httpclient:4.5.10
     |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.12
     |    |    |    +--- commons-logging:commons-logging:1.2
     |    |    |    \--- commons-codec:commons-codec:1.11 -> 1.13
     |    |    +--- org.apache.httpcomponents:httpcore:4.4.12
     |    |    +--- org.apache.httpcomponents:httpasyncclient:4.1.4
     |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.10 -> 4.4.12
     |    |    |    +--- org.apache.httpcomponents:httpcore-nio:4.4.10 -> 4.4.12
     |    |    |    |    \--- org.apache.httpcomponents:httpcore:4.4.12
     |    |    |    +--- org.apache.httpcomponents:httpclient:4.5.6 -> 4.5.10 (*)
     |    |    |    \--- commons-logging:commons-logging:1.2
     |    |    +--- org.apache.httpcomponents:httpcore-nio:4.4.12 (*)
     |    |    +--- commons-codec:commons-codec:1.11 -> 1.13
     |    |    \--- commons-logging:commons-logging:1.1.3 -> 1.2
     |    +--- org.codelibs.elasticsearch.lib:ssl-config:7.10.2
     |    +--- org.apache.httpcomponents:httpasyncclient:4.1.4 (*)
     |    +--- org.apache.httpcomponents:httpclient:4.5.10 (*)
     |    +--- org.apache.httpcomponents:httpcore:4.4.12
     |    \--- org.apache.httpcomponents:httpcore-nio:4.4.12 (*)
     +--- org.codelibs.elasticsearch.module:repository-url:7.10.2
     +--- org.codelibs.elasticsearch.module:transport-netty4:7.10.2
     |    +--- io.netty:netty-buffer:4.1.49.Final
     |    |    \--- io.netty:netty-common:4.1.49.Final
     |    +--- io.netty:netty-codec:4.1.49.Final
     |    |    +--- io.netty:netty-common:4.1.49.Final
     |    |    +--- io.netty:netty-buffer:4.1.49.Final (*)
     |    |    \--- io.netty:netty-transport:4.1.49.Final
     |    |         +--- io.netty:netty-common:4.1.49.Final
     |    |         +--- io.netty:netty-buffer:4.1.49.Final (*)
     |    |         \--- io.netty:netty-resolver:4.1.49.Final
     |    |              \--- io.netty:netty-common:4.1.49.Final
     |    +--- io.netty:netty-codec-http:4.1.49.Final
     |    |    +--- io.netty:netty-common:4.1.49.Final
     |    |    +--- io.netty:netty-buffer:4.1.49.Final (*)
     |    |    +--- io.netty:netty-transport:4.1.49.Final (*)
     |    |    +--- io.netty:netty-codec:4.1.49.Final (*)
     |    |    \--- io.netty:netty-handler:4.1.49.Final
     |    |         +--- io.netty:netty-common:4.1.49.Final
     |    |         +--- io.netty:netty-resolver:4.1.49.Final (*)
     |    |         +--- io.netty:netty-buffer:4.1.49.Final (*)
     |    |         +--- io.netty:netty-transport:4.1.49.Final (*)
     |    |         \--- io.netty:netty-codec:4.1.49.Final (*)
     |    +--- io.netty:netty-common:4.1.49.Final
     |    +--- io.netty:netty-handler:4.1.49.Final (*)
     |    +--- io.netty:netty-resolver:4.1.49.Final (*)
     |    \--- io.netty:netty-transport:4.1.49.Final (*)
     +--- args4j:args4j:2.33
     +--- org.apache.logging.log4j:log4j-api:2.11.1
     +--- org.apache.logging.log4j:log4j-core:2.11.1 (*)
     +--- org.codelibs:curl4j:1.2.4
     |    \--- commons-io:commons-io:2.6
     +--- org.locationtech.jts:jts-core:1.15.0
     \--- org.locationtech.spatial4j:spatial4j:0.7
```
Are you saying that the lucene version used in elasticsearch should match the runner's lucene version?

im use 
compile ('org.elasticsearch:elasticsearch:7.10.2')
testImplementation (group: 'org.codelibs', name: 'elasticsearch-cluster-runner', version: '7.10.2.0')

**Comment by sangkyunkim89** [comment]
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.json.JsonXContent;

![image](https://user-images.githubusercontent.com/65607130/148688162-dc799df1-7659-427b-ba18-f3256b7dc779.png)

I matched the Lucene version, but the above error occurred and the location of the package was changed as the version went up, but yours did not change.

import org.elasticsearch.xcontent.XContentType;

**Comment by marevol** [comment]
elasticsearch depends on Lucene. elasticsearch 7.10.2 use Lucene 8.7.0, so you should use the same Lucene.
I think this is just a dependency problem, not our library. Therefore, you need to clean your dependency up and use the correct version.

**Comment by sangkyunkim89** [comment]
i want implementation group: 'org.elasticsearch', name: 'elasticsearch', version: '7.16.2'

So what version of runner should I use?

**Comment by sangkyunkim89** [comment]
@marevol 
I ran the tests using Elasticsearch 7.16.2 and runner 7.10.2.0

error

org/elasticsearch/common/xcontent/XContentBuilder
java.lang.NoClassDefFoundError: org/elasticsearch/common/xcontent/XContentBuilder
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
	at org.kohsuke.args4j.ClassParser.parse(ClassParser.java:20)
	at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:96)
	at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:325)
	at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:315)

Now the error is not the problem with Lucene, it is using the Xbuilder of es in the runner, but it is an outdated package.
Do you want to support the current version?

**Comment by sangkyunkim89** [comment]
I downgraded it in the end, but please be able to use it in the latest version!!

**Comment by marevol** [comment]
See https://maven.codelibs.org/org/codelibs/elasticsearch-cluster-runner/
