### ISSUE TITLE
Sonatype Nexus cannot mirror CodeLibs Maven repository

### ISSUE THREAD

**Issue by sabi0** [codelibs/elasticsearch-cluster-runner#52]
Trying to add a proxy for CodeLibs repository to our company's Sonatype Nexus results in this error in the log:
```
2023-07-06 11:29:21,777+0200 ERROR [qtp195033295-194986798] ad85560 org.sonatype.nexus.rest.NexusApplication - Unhandled exception or error intercepted
java.lang.StringIndexOutOfBoundsException: String index out of range: -6
        at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:935)
        at java.lang.StringBuilder.substring(StringBuilder.java:76)
        at org.sonatype.nexus.plugins.rrb.parsers.HtmlRemoteRepositoryParser.getLinkUrl(HtmlRemoteRepositoryParser.java:173)
        at org.sonatype.nexus.plugins.rrb.parsers.HtmlRemoteRepositoryParser.extractLinks(HtmlRemoteRepositoryParser.java:110)
        at org.sonatype.nexus.plugins.rrb.MavenRepositoryReader.parseResult(MavenRepositoryReader.java:147)
        at org.sonatype.nexus.plugins.rrb.MavenRepositoryReader.extract(MavenRepositoryReader.java:105)
        at org.sonatype.nexus.plugins.rrb.RemoteBrowserResource.get(RemoteBrowserResource.java:138)
```

This seems similar to this issue:
https://stackoverflow.com/questions/44828352/how-to-solve-the-issue-of-nexus-not-finding-artifacts-from-added-repository-for

I wonder if you could do anything about this from your side?

**Comment by sabi0** [comment]
The error above is apparently caused by trying to browse CodeLibs repository via Nexus UI ("Browse Remote" tab).
Access to the artifacts is working fine (there was another configuration error preventing it initially).

Feel free to close this ticket if you think browsing repository content is not something you want to bother with.
